name: timvieclam_mobile_flutter
description: Demo Flutter app for TimViecLam
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
